### ISSUE TITLE
Problems again with fb_team_goal_logs

### ISSUE THREAD

**Issue by Jes-Lop** [JaseZiv/worldfootballR#192]
If you use fb_team_goal_logs(team_urls = "https://fbref.com/en/squads/a0435291/Granada-Stats", for_or_against = "for") you get this error message:
Error in `.data[["Body.Part"]]`:
! Column `Body.Part` not found in `.data`.
Run `rlang::last_error()` to see where the error occurred.

**Comment by JaseZiv** [comment]
Ah yes I know what's going on here.

Will work on a fix over the next few days.

Thanks

**Comment by JaseZiv** [comment]
Tagging @szfh here...

The issue here is that `Body.Part` isn't available for some leagues/divisions. This would have worked without error for Granada last season as they were in LaLiga, but errors this season with them in LaLiga2...

Just need to add in error handling to account for when it is and isn't present.
