### ISSUE TITLE
fotmob_get_league_matches for previous seasons

### ISSUE THREAD

**Issue by Zakgas** [JaseZiv/worldfootballR#250]
Hi,

Is there a way of using the function above for previous seasons?

Best,
zakgas

**Comment by tonyelhabr** [comment]
Hey, thanks for your interest. The current version of `fotmob_get_league_matches` does not support retrieving data for past seasons. This is because Fotmob did not have an API parameters for this at the time the function was written. However, I've just checked their site again and it seems like it should be possible now, e.g. [here](https://www.fotmob.com/api/leagues?id=47&ccode3=USA&season=2014%2F2015) for the 2014/15 EPL season.

I'll leave this issue open until we've added functionality to support this.

**Comment by Zakgas** [comment]
Hi Tony,

Many thanks for getting back to me. How would I be able to add the parameters to the function manually? Is there a way of exporting this link/CSV to the function?

Best,
zakgas
