### ISSUE TITLE
how I  downgrade version 0.6.4.0 to other version

### ISSUE THREAD

**Issue by Gyracat** [JaseZiv/worldfootballR#312]

**Comment by tonyelhabr** [comment]
Assuming this is because you want to get the version of the package before the fotmob functions were removed, you'd need to go and find the last commit prior to the removal, which is `60a9fc82c342725f3f4ce5968e40a02e76977436` (click the "Copy" button on the commit).

![commits](https://github.com/JaseZiv/worldfootballR/assets/15663460/c978a9cd-7bd3-4702-b3f8-78fb10fd7db6)


Then,

```r
`remotes::install_github("JaseZiv/worldfootballR@60a9fc82c342725f3f4ce5968e40a02e76977436")
```
