### ISSUE TITLE
I found bug in this function <fb_league_stats> 

### ISSUE THREAD

**Issue by Gyracat** [JaseZiv/worldfootballR#318]
I found bug in this function <fb_league_stats>

Example Code
`test <-fb_league_stats(
  country ="ENG",
  gender ="M",
  season_end_year = 2023,
  tier = "1st",
  stat_type = "passing_types",
  team_or_player ="player",
  time_pause = 3,
  rate = purrr::rate_backoff(max_times = 3)
)`

<img width="365" alt="Screenshot 2566-08-22 at 22 58 28" src="https://github.com/JaseZiv/worldfootballR/assets/79399115/e17e3a3f-db38-4a39-87a8-97df79134c92">

</p>
</details>

**Comment by tonyelhabr** [comment]
I don't think this is really a bug. This function is "experimental" and can be highly dependent on

1. your internet connection
2. FBRef's server latency

On the backend, we use chromote and have to wait for the table to be loaded via JavaScript on the page. this is the only function like this in the package AFAIK.

**Comment by tonyelhabr** [comment]
for transparency, i basically copied over a lot of the rvest / promise for `fb_league_stats()` (see `worldfootballr_chromote_session()`) from [this branch](https://github.com/tidyverse/rvest/pull/362) in the {rvest} package. that branch has been in draft state for months, seemingly because it's never completely worked properly

**Comment by tonyelhabr** [comment]
I've intentionally left this issue open to give notice that we're aware that this function is unreliable. I'm not sure there's a great solution without using Selenium, which we've implicitly decided to not use, so as to reduce the scope of this package.

I think the reason why the function sometimes works but sometimes doesn't is due to server latency on FBref's end, but I'm not entirely sure. The function relies on `{promises}` for async behavior, which can be very dependent on Internet connection and server response time.

**Comment by SeriyBg** [comment]
Thanks for the answer @tonyelhabr!
One more note, that may help in solving this issue. I found a workaround by using `fb_big5_advanced_season_stats(season_end_year= c(2024), stat_type= "shooting", team_or_player= "player")` instead and filtering by the league name after. The fact that the `fb_big5_advanced_season_stats` is working while `fb_league_stats` isn't might indicate that this is not the server latency issue. However, this is only my guess 😃

**Comment by tonyelhabr** [comment]
Issue is being archived.
