### ISSUE TITLE
Ability to load and choose position based scouting report, for players with multiple positions

### ISSUE THREAD

**Issue by zshanhamid** [JaseZiv/worldfootballR#35]
Hi , firstly let me say this is a very useful and fun package to use, so thank you @JaseZiv  

An issue I've found is currently attempting to scrape data on players with multiple positions will result in the following error :
![image](https://user-images.githubusercontent.com/63023110/120080605-c4cfc200-c087-11eb-873a-e15b308ac02d.png)
It would seem the package isn't sure which position report should be used, although I'm just guessing here.
This unfortunately means data scraping for players with multiple positions on fbref ,currently appears not possible.
Additionally, such a functionality that allows for choosing which position based scouting report to scrape would facilitate some interesting data analysis possibilities.

 Anyway, I hope you keep up this project, I'm sure it helps a good number of statistical minded footy fans like me.

**Comment by JaseZiv** [comment]
Hi there,

Thanks for the feedback and identifying this issue.

Can you please provide the exact code you've written here as an example?

I'll start investigating the issue.

Thanks

**Comment by JaseZiv** [comment]
I've actually worked out what your problem was - you need to pass either "primary" or "secondary" to the `pos_versus` argument.

`Xhaka_primary <- fb_player_scouting_report(player_url = "https://fbref.com/en/players/e61b8aee/Granit-Xhaka", pos_versus = "primary")`

`Xhaka_secondary <- fb_player_scouting_report(player_url = "https://fbref.com/en/players/e61b8aee/Granit-Xhaka", pos_versus="secondary")`
