### ISSUE TITLE
fb_team_player_stats Error in 'map()'

### ISSUE THREAD

**Issue by kidshiva** [JaseZiv/worldfootballR#371]
Hello,

running fb_team_player_stats and getting a new error I havent seen before

Error in `map()`:
ℹ In index: 1.
Caused by error in `xml_nodeset()`:
! Expecting an external pointer: [type=NULL]

team_urls <- fb_teams_urls(league_url)
test <- fb_team_player_stats(team_urls,
                             stat_type = "passing",
                             time_pause = 4)

Using WorldFootballR version 0.6.5.3

**Comment by NikolasSotiriou** [comment]
Another user here. I seem to find the same problem so I didn't want to open a new issue. I'm also using the latest version of the package. My reproducible example is the following. Note that this bug seems to come and go, i.e. the function may work one day and not the next, so I guess a change in what it is scraping is what is throwing it off. Any help by the developers would be appreciated.

> fb_team_player_stats(fb_teams_urls("https://fbref.com/en/comps/9/Premier-League-Stats"), stat_type="misc")
Error in `map()`:
ℹ In index: 1.
Caused by error in `xml_nodeset()`:
! Expecting an external pointer: [type=NULL]
Run `rlang::last_trace()` to see where the error occurred.

**Comment by JaseZiv** [comment]
These intermittent issues might just be something inherent when scraping unfortunately.

I can't recreate the errors with the above examples.

**Comment by NikolasSotiriou** [comment]
Yeah, I expected this, but I thought I should mention it as well. Thank you for looking at it.
