### ISSUE TITLE
function get_match_results

### ISSUE THREAD

**Issue by colbai** [JaseZiv/worldfootballR#86]
The function get_match_results does not work for seasons in progress. I believe it because it is trying to pull match URLs for each match, and they do not exist for matches yet to be played.

get_match_results("ENG", "M", 2022, "1st")
Error in `mutate_cols()`:
! Problem with `mutate()` column `MatchURL`.
i `MatchURL = match_urls`.
i `MatchURL` must be size 380 or 1, not 363.

**Comment by JaseZiv** [comment]
What version are you using?

The current dev version `0.4.9.3000` doesn't have this issue as it was a bug fixed in one of the minor dev releases.

Use `devtools::install_github("JaseZiv/worldfootballR")` to install to the up-to-date version and let me know how it goes before i close this issue off.

Thanks for reaching out!

**Comment by colbai** [comment]
My mistake, I thought I tried reinstalling to update. The function works now. Thanks so much!
